package ElevadorPOO;

import java.util.Random;

public class Elevador {
    Random rd = new Random();
    boolean movimento = false;
    boolean rodando = true;

    public void elevador() {
        int andar = 0;
        int passageiros = 0;
        int acao = 0;
        
        while (rodando == true) {
            movimento = false;

            // Matrizes
            if (andar == 0 && passageiros == 3) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|        0       0        0            |");
                System.out.println("|       ||      ||       ||            |");
                System.out.println("|       /|      /|       /|            |");

            } else if (andar == 0 && passageiros == 2) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                0        0            |");
                System.out.println("|               ||       ||            |");
                System.out.println("|               /|       /|            |");
            } else if (andar == 0 && passageiros == 1) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                         0            |");
                System.out.println("|                        ||            |");
                System.out.println("|                        /|            |");
            } else if (andar == 0 && passageiros == 0) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 1 && passageiros == 3) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|        0       0        0            |");
                System.out.println("|       ||      ||       ||            |");
                System.out.println("|       /|      /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 1 && passageiros == 2) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                0        0            |");
                System.out.println("|               ||       ||            |");
                System.out.println("|               /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 1 && passageiros == 1) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                         0            |");
                System.out.println("|                        ||            |");
                System.out.println("|                        /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 1 && passageiros == 0) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 2 && passageiros == 3) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|        0       0        0            |");
                System.out.println("|       ||      ||       ||            |");
                System.out.println("|       /|      /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 2 && passageiros == 2) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                0        0            |");
                System.out.println("|               ||       ||            |");
                System.out.println("|               /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 2 && passageiros == 1) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                         0            |");
                System.out.println("|                        ||            |");
                System.out.println("|                        /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 2 && passageiros == 0) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 3 && passageiros == 3) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|        0       0        0            |");
                System.out.println("|       ||      ||       ||            |");
                System.out.println("|       /|      /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 3 && passageiros == 2) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                0        0            |");
                System.out.println("|               ||       ||            |");
                System.out.println("|               /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 3 && passageiros == 1) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                         0            |");
                System.out.println("|                        ||            |");
                System.out.println("|                        /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 3 && passageiros == 0) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 4 && passageiros == 3) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|        0       0        0            |");
                System.out.println("|       ||      ||       ||            |");
                System.out.println("|       /|      /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 4 && passageiros == 2) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                0        0            |");
                System.out.println("|               ||       ||            |");
                System.out.println("|               /|       /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 4 && passageiros == 1) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                         0            |");
                System.out.println("|                        ||            |");
                System.out.println("|                        /|            |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
            } else if (andar == 4 && passageiros == 0) {
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|    ------------------------------    |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|______________________________________|");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");
                System.out.println("|                                      |");

                // Ação Aleatória
                while (movimento == false) {
                    acao = rd.nextInt(1, 5);
                    if (acao == 1 && andar < 5) {
                        andar++;
                        movimento = true;
                    } else if (acao == 2 && andar > 0) {
                        andar--;
                        movimento = true;
                    } else if (acao == 3 && passageiros < 3) {
                        passageiros++;
                        movimento = true;
                    } else if (acao == 4 && passageiros > 0) {
                        passageiros--;
                        movimento = true;
                    }

                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                    }

                    // Limpa o console
                    System.out.print("\033[H\033[2J");
                    System.out.flush();
                }
            }

            // Ação Aleatória
            while (movimento == false) {
                acao = rd.nextInt(1, 5);
                if (acao == 1 && andar <= 3) {
                    andar++;
                    movimento = true;
                } else if (acao == 2 && andar >= 1) {
                    andar--;
                    movimento = true;
                } else if (acao == 3 && passageiros <= 2) {
                    passageiros++;
                    movimento = true;
                } else if (acao == 4 && passageiros >= 1) {
                    passageiros--;
                    movimento = true;
                }

                try {
                    Thread.sleep(300);
                } catch (InterruptedException e) {
                }
            }

            // Limpa o console
            System.out.print("\033[H\033[2J");
            System.out.flush();
        }
    }
}
